add_task_id = "id@@com.splendapps.splendo:id/fabAddTask"
task_name_input_id = "id@@com.splendapps.splendo:id/edtTaskName"
calendar_icon_id = "id@@com.splendapps.splendo:id/btnSetD"

inside_calendar_ok_button_x = "xpath@@//android.widget.Button[@resource-id='android:id/button1']"
time_icon_x = "xpath@@//android.widget.ImageView[@resource-id='com.splendapps.splendo:id/btnSetT']"
inside_time_icon_ok_button_x = "xpath@@//android.widget.Button[@resource-id='android:id/button1']"
save_tick_mark_icon_task_id = "id@@com.splendapps.splendo:id/fabSaveTask"
in_the_task_c_drop_down_id = "id@@com.splendapps.splendo:id/spinnerLists"
personal_x = "xpath@@//android.widget.TextView[@text='Personal']"
shopping_x = "xpath@@//android.widget.TextView[@text='Shopping']"
wishlist_x = "xpath@@//android.widget.TextView[@text='Wishlist']"
work_x = "xpath@@//android.widget.TextView[@text='Work']"
quick_task_input_id = "id@@com.splendapps.splendo:id/etQuickTask"
quick_task_save_icon_id = "id@@com.splendapps.splendo:id/ivAddQuickTask"
three_dot_more_option_id = "id@@More options"
in_three_dot_task_list_x = "xpath@@//android.widget.TextView[@resource-id='com.splendapps.splendo:id/title' and @text='Task Lists']"
all_list_id = "id@@com.splendapps.splendo:id/spinnerToolbar"
add_new_list_x = "xpath@@//android.widget.TextView[@resource-id='com.splendapps.splendo:id/navLineName' and @text='New List']"
new_list_name_input_x = "xpath@@//android.widget.EditText[@text='Enter List Name']"
new_list_add_button_x = "xpath@@//android.widget.Button[@resource-id='android:id/button1']"
for_click_on_task_x = "xpath@@(//android.widget.RelativeLayout[@resource-id='com.splendapps.splendo:id/task_list_item'])[1]/android.widget.LinearLayout"
back_button_x = "xpath@@//android.widget.ImageButton[@content-desc='Navigate up']"
list_delete_icon_x = "xpath@@(//android.widget.ImageView[@content-desc='Delete'])[1]" #I will able to change the list number
delete_button_x = "xpath@@//android.widget.Button[@resource-id='android:id/button1']"
edit_pen_icon_x = "xpath@@(//android.widget.ImageView[@content-desc='Edit'])[1]" #I will able to change the list number

new_created_task_x = "xpath@@//android.widget.TextView[@resource-id='com.splendapps.splendo:id/task_name']"
close_task_id = "id@@com.splendapps.splendo:id/checkDone"
empty_list_id = "id@@com.splendapps.splendo:id/tvEmpty"